In [1]:
html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were </p>
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
<p>and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

In [2]:
# 导入库
from bs4 import BeautifulSoup
# 实例化
soup = BeautifulSoup(html_doc, 'html.parser')


In [11]:
soup.find_all(string="Elsie")

['Elsie']

In [13]:
import re

In [15]:

soup.find_all(string="Elsie")
# [u'Elsie']

soup.find_all(string=["Tillie", "Elsie", "Lacie"])
# [u'Elsie', u'Lacie', u'Tillie']

soup.find_all(string=re.compile("Dormouse"))
[u"The Dormouse's story", u"The Dormouse's story"]

def is_the_only_string_within_a_tag(s):
    """Return True if this string is the only child of its parent tag."""
    return (s == s.parent.string)

soup.find_all(string=is_the_only_string_within_a_tag)
# [u"The Dormouse's story", u"The Dormouse's story", u'Elsie', u'Lacie', u'Tillie', u'...']

["The Dormouse's story", "The Dormouse's story"]

In [26]:
soup.find_all(string=re.compile('three'))

['Once upon a time there were three little sisters; and their names were ']

In [28]:
soup.find_all('a',string=re.compile('Lacie'))

[<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>]

In [38]:
soup.find_all("a", limit=2)


[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>]

In [116]:
html_doc = '''
<div id='aa'>
    <span id='bb'></span>
    <div id='cc'>
        <span id='dd'></span>
    </div>
</div>
'''

In [117]:
soup = BeautifulSoup(html_doc, 'html.parser')

In [118]:
soup.div.find_all('span')

[<span id="bb"></span>, <span id="dd"></span>]

In [120]:
soup.div.find_all('span',recursive=False)

[<span id="bb"></span>]

In [58]:
print(soup.prettify())

<html>
 <body>
  <div id="aa">
   <div id="bb">
    <div id="cc">
    </div>
   </div>
  </div>
 </body>
</html>


In [73]:
soup.html.find_all('div')

[<div id="aa">
 <div id="bb">
 <div id="cc">
 </div>
 </div>
 </div>,
 <div id="bb">
 <div id="cc">
 </div>
 </div>,
 <div id="cc">
 </div>]

In [122]:
soup.select('div>span')

[<span id="bb"></span>, <span id="dd"></span>]

In [1]:
import numpy as np

In [13]:
x = np.array([
    [1],
    [3]
])
y = np.array([
    [-2],
    [4]
])

In [17]:
np.sqrt((x-y).T @  (x-y))

array([[3.16227766]])

In [4]:
y

array([[ 4],
       [-3]])

In [5]:
x.T

array([[-2,  2]])

In [6]:
x.T @ y

array([[-14]])

In [7]:
np.dot(x.T,y)

array([[-14]])

In [8]:
x = np.array([
    [3],
    [4]
])

In [10]:
np.sqrt(x.T @ x )

array([[5.]])

In [11]:
np.sqrt(np.dot(x.T,x))

array([[5.]])

In [18]:
np.linalg.norm(x-y,2)

3.1622776601683795

In [19]:
x = np.array([[2], [0]])
y = np.array([[0], [2]])


In [20]:
cos_theta =( x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2) )

In [21]:
cos_theta

array([[0.]])

In [2]:
import numpy

values = [13,21,21,40,42,48,55,72]

x = numpy.percentile(values, 65)

print(x)

41.0


In [3]:
import numpy as np

values = [13,21,21,40,42,48,55,72]

q_1,q_3 = np.quantile(values, [0.25,0.75])

In [5]:
q_3 - q_1

28.75

In [6]:
from scipy import stats

values = [13,21,21,40,42,48,55,72]

x = stats.iqr(values)

print(x)

28.75


In [7]:
import numpy

values = [4,11,7,14]

x = numpy.std(values)

print(x)

3.8078865529319543


In [12]:
import numpy

values = [4,11,7,14]

x = numpy.std(values, ddof=1)

print(x)

4.396968652757639


In [23]:
# base vector
y = np.array([[3],
              [2]])

x = np.array([[1],
              [3]])

P = (y @ y.T)/(y.T @ y)

In [14]:
x_x = P @ x

In [22]:
x_x

array([[2.07692308],
       [1.38461538]])

array([[9.]])

In [27]:
y.T @ (x - x_x)

array([[8.8817842e-16]])

In [30]:
np.dot(y.T,(x - x_x))

array([[8.8817842e-16]])