In [4]:
# 导入机器学习算法：随机森林分类器
from sklearn.ensemble import RandomForestClassifier
# 实例化，配置相关模型参数
clf = RandomForestClassifier(random_state=0)
# 构造一个训练数据，2个样本，每个样本3个特征
X = [[ 1,  2,  3],  
     [11, 12, 13]]
# 样本的类别
y = [0, 1]

# 训练
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [5]:
# 预测一下测试数据的类别
clf.predict(X)

array([0, 1])

In [3]:
# 预测一下测试数据
clf.predict([[4, 5, 6], [14, 15, 16]]) 

array([0, 1])

In [1]:
import numpy as np

In [3]:
# 赋值x,y为向量[1,2,3]
x = y = np.array([[1],
                  [2],
                  [3]])

In [5]:
x + y

array([[2],
       [4],
       [6]])

In [7]:
np.add(x,y)

array([[2],
       [4],
       [6]])

In [8]:
x = 3
y = np.array([
    [3],
    [4],
    [5],
    [6]
])

In [9]:
x*y

array([[ 9],
       [12],
       [15],
       [18]])

In [10]:
a,b = 2,3

In [15]:
x,y = np.array([[2],[3]]), np.array([[4],[5]])

In [17]:
a * x + b * y

array([[16],
       [21]])

In [18]:
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])


In [20]:
np.dot(x.T,y)

array([[-14]])

In [21]:
x.T @ y


array([[-14]])

In [18]:
import numpy as np

In [9]:
a = np.array([[3],[-4],[-5]])

In [10]:
np.linalg.norm(a,np.inf)

5.0

In [42]:
A = np.array([
    [0,2],
    [1,4],
    [3,1],    
])
B = np.array([
    [0,2],
    [1,4]
])
I = np.identity(2)

In [44]:
A * I

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [5]:
0,2 3,-3  = -6
0,2 1,2 = 4
1,4 3,-3 3 -12 =-9
1,4 1,2 2 8 = 9

SyntaxError: invalid syntax (<ipython-input-5-5ae7627b0717>, line 1)

In [17]:
np.dot(A,B)

array([[ 2,  8],
       [ 4, 18],
       [ 1, 10]])

In [29]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

In [30]:
A_i = np.linalg.inv(A)

In [31]:
A_i

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [37]:
np.round(A @ A_i )


array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [38]:
np.round(A_i @ A )


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

array([[ 1.00000000e+00,  3.55271368e-15,  3.55271368e-15],
       [ 6.66133815e-16,  1.00000000e+00,  7.77156117e-16],
       [-8.88178420e-16, -4.44089210e-16,  1.00000000e+00]])

In [40]:
A = np.array([[1, 3, 5],
              [2, 4, 6]])

In [41]:
A.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
A = np.array([[1, 2],
              [3, 4]])

In [46]:
B = np.array([[5, 6],
              [7, 8]])

In [47]:
A*B

array([[ 5, 12],
       [21, 32]])

In [48]:
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

In [50]:
import numpy as np

In [51]:
A = np.array([
    [1,-2,3],
    [-1,3,0],
    [2,-5,5]    
])

In [52]:
A

array([[ 1, -2,  3],
       [-1,  3,  0],
       [ 2, -5,  5]])

In [53]:
y = np.array([
    [9],
    [-4],
    [17]
])

In [54]:
y

array([[ 9],
       [-4],
       [17]])

In [55]:
np.linalg.solve(A,y)

array([[ 1.],
       [-1.],
       [ 2.]])